---
functional:
  - Пользователь имеет возможность создать баттл
  - Пользователь имеет возможность выбрать любой доступный баттл и принять участие
  - У участников одинаковые условия задачи за фиксированное время
  - Каждый участник может выбрать язык программирования из списка, на котором будет решать задачу
  - Можно менять язык программирования во время решения
  - Победа присуждается игроку который верно выполнил условия задачи за меньшее время
  - За победы и участие пользователи получают очки, формируется общий рейтинг
  - Во время баттла игроки видят друг у друга редактор с кодом, вывод тестов
  - При создании баттла доступны настройки - уровень сложности, соперник (участник, бот, пригласить по ссылке друга), задача, таймер, тэг
  - Создавая баттл, задачу можно не указывать - по умолчанию она будет подобрана рандомно
  - Пользователи имеют возможность следить за ходом активного баттла других игроков
  - Задачи даны на двух языках — русском и английском
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь имеет возможность принять участие в баттле без регистрации
  - Пользователь имеет возможность регистрации в системе с помощью E-mail, GitHub, Discord
  - Пользователь имеет доступ к личному кабинету со своей статистикой и настройками
  - Возможность ознакомления нового пользователя с функционалом и возможностями
  - На главной странице отображается список активных баттлов с никнеймами участников, уровнем сложности и статусом
  - Пользователь имеет возможность сдаться во время баттла