---
functional:
  - Пользователь может создать баттл
  - Желающий может присоединиться к баттлу
  - У участников одинаковые условия задачи за фиксированное время
  - Каждый участник может выбрать язык программирования из списка, на котором будет решать задачу
  - Можно менять язык программирования во время решения
  - В процессе решения есть возможность проверить свой код и переписать решение, если баттл еще продолжается
  - Победа присуждается игроку который верно выполнил условия задачи за меньшее время
  - За победы и участие пользователи получают очки, формируется общий рейтинг
  - Во время баттла игроки видят друг у друга редактор с кодом, вывод тестов
  - При создании баттла доступны настройки - уровень сложности, соперник (участник, бот, пригласить по ссылке друга), задача, таймер 
  - Создавая баттл, задачу можно не указывать - по умолчанию она будет подобрана рандомно
  - Другие пользователи могут следить за ходом баттла
  - Задачи даны на двух языках — русском и английском
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - На главной странице табло баттлов в процессе, ожидающих соперников с никнеймами участвующих игроков и уровнем сложности, общим рейтингом
  - Доступна регистрация на сайте и личный кабинет со статистикой
  - Участники баттла и наблюдающие не могут вводить и редактировать код в терминале соперника
  - Возможность отменить созданный баттл и приглашение
  - Возможность ознакомления нового пользователя с функционалом и возможностями