---
functional:
  - Пользователь имеет возможность создать баттл
  - Пользователь имеет возможность принять участие в баттле
  - У участников одинаковые условия задачи за фиксированное время
  - Задачи даны на двух языках — русском и английском
  - Каждый участник может выбрать язык программирования
  - Победа присуждается игроку который верно выполнил условия задачи за меньшее время
  - За победы и участие пользователи получают очки, формируется общий рейтинг
  - Игроки видят два редактора - свой и соперника. Каждый игрок видит код своего соперника в режиме он-лайн.
  - Пользователи имеют возможность следить за ходом активного баттла других игроков
  - В игре есть чат, в котором общаются зарегистрированные пользователи
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - При создании баттла доступны настройки - уровень сложности, соперник, задача, таймер
  - Пользователь имеет возможность регистрации в системе с помощью E-mail, GitHub, Discord
  - Пользователь имеет доступ к личному кабинету со своей статистикой и настройками
  - Пользователь имеет возможность сдаться, взять реванш
  - Пользователь имеет возможность менять язык программирования во время решения
  - Возможность ознакомления нового пользователя с функционалом и возможностями
  - Создавая баттл, задачу можно не указывать - по умолчанию она будет подобрана рандомно
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
  - На сайте есть список пользователей онлайн 